version: '3.4'

services:
  patisserie:
    image: patisserie
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./.env:/usr/src/app/.env

